name: watch_hub
description: "Watch Hub - Premium Online Watch Store"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.4

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^15.1.2

  # UI & Styling
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  device_preview: ^1.1.1
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  animated_text_kit: ^4.2.3

  # Utilities
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
